name: postgres_builder
description: A tool designed to make writing PostgreSQL statements easier without writing them by hand.
version: 2.2.1
repository: https://github.com/Morel-Tech/dart_postgres_builder
issue_tracker: https://github.com/Morel-Tech/dart_postgres_builder/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  json_annotation: ^4.8.1
  meta: ^1.9.0
  postgres: ^3.0.0
  recase: ^4.1.0

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.19.2
  very_good_analysis: ^5.0.0
